# Generated by Django 6.1 on 2026-08-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Futebol', 'Futebol'), ('NBA', 'NBA'), ('Games', 'Games')], max_length=50),
        ),
    ]
