# Generated by Django 6.1 on 2026-08-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='publicado', max_length=20),
        ),
    ]
