# Generated by Django 6.1 on 2026-08-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_noticia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
